### ISSUE TITLE
flux RSS

### ISSUE THREAD

**Issue by qwertygc** [mknexen/shaarli-river#1]
Salut !
 Une idée serait d'avoir un flux RSS qui résumerai chaque jour les top liens !
q.

**Comment by mknexen** [comment]
Bonne idée, un flux "des liens repartagés": à partir du moment où le lien est repartagé au moins une fois il apparaît dans le flux

J'ai commencé de bricoler quelque chose mais c'est pas encore ça:
https://nexen.mkdir.fr/shaarli-river/top.php?do=rss

RSS untouched: https://nexen.mkdir.fr/shaarli-api/bestlinks?format=rss
JSON: https://nexen.mkdir.fr/shaarli-api/bestlinks?pretty=1

J'vais continuer de bosser dessus, ça sera surement amener à changer

**Comment by mknexen** [comment]
Allez hop vendu chaque jour le top de la veille: https://nexen.mkdir.fr/shaarli-river/top.php?do=rss
C'est plus propre comme ça c'est vrai
