### ISSUE TITLE
Possibilitée de filtrer une API.

### ISSUE THREAD

**Issue by yjarosz** [mknexen/shaarli-river#3]
Hello,
ça serai cool de pouvoir s'installer une river sans avoir à installer l'API et filtrer les liens que l'on veut recevoir.
Un pote à moi n'a pas les moyens de s'installer l'API et il trouve certains des liens qui sont sur ta river inintéressant.
Je lui ai fait un petit hack pour lui filtrer les réponses de l'API à la volée sur [mon fork](https://github.com/yjarosz/shaarli-river/blob/master/includes/ShaarliApiClient.php#L102). C'est moche mais j'ai fait ça vite... 

Idée à creuser si tu permets que l'on se serve de ton API.

**Comment by mknexen** [comment]
J'ai rajouté la possibilité de filtrer sur les ids des shaarlis sur l'API.
En gros le hack peut se faire plus facilement en modifiant cette ligne https://github.com/mknexen/shaarli-river/blob/master/index.php#L10
par

``` php
    $api = new ShaarliApiClient( SHAARLI_API_URL );
    $rows = $api->latest(array('ids' => array(
        1, // sebsauvage
        6 // Horyax
    )));
```

à voir comment l'intègrer pour que ça soit configurable.

> Idée à creuser si tu permets que l'on se serve de ton API.

Bien sûr que vous pouvez vous servir de l'API c'est fait pour ça =)

**Comment by mknexen** [comment]
Job done du coup : https://github.com/mknexen/shaarli-river/commit/a6c143954d3b037461983759c369519f0d8aeab5#diff-f40b3f4896dbb934baebd65ee043eeb0R25
